# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pronunciation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fluency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grammar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vocabulary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('global_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
