# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tspeak_sessions', '0001_initial'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='tspeak_sessions.vocalsession'),
        ),
    ]
