# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['user', '-created_at'], name='scores_user_id_bf2900_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['global_score'], name='scores_global__ec2366_idx'),
        ),
    ]
