# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('native_language', models.CharField(choices=[('wolof', 'Wolof'), ('pulaar', 'Pulaar / Peul'), ('bambara', 'Bambara'), ('dioula', 'Dioula'), ('serer', 'Sérère'), ('french', 'Français'), ('other', 'Autre')], default='french', max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Débutant'), ('elementary', 'Élémentaire'), ('intermediate', 'Intermédiaire'), ('upper_intermediate', 'Intermédiaire avancé'), ('advanced', 'Avancé')], default='beginner', max_length=30)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('streak_last_date', models.DateField(blank=True, null=True)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('avg_pronunciation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_fluency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_grammar', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_vocabulary', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(max_length=100)),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(default='🏅', max_length=10)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', 'badge_type'], name='badges_user_id_55ac2b_idx')],
                'unique_together': {('user', 'badge_type')},
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['xp_total'], name='users_xp_tota_51c686_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['streak_days'], name='users_streak__97e511_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['native_language'], name='users_native__c4bcf9_idx'),
        ),
    ]
