# Generated by Django 4.2.16 on 2026-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="user",
            name="age_range",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="learning_goal",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["first_name"], name="users_first_n_0c5a67_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_name"], name="users_last_na_5e9a3c_idx"),
        ),
    ]
