# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pitch', 'Pitch Investisseur'), ('interview', "Entretien d'embauche"), ('client_call', 'Appel client'), ('crisis', 'Gestion de crise'), ('negotiation', 'Négociation'), ('presentation', 'Présentation'), ('networking', 'Networking')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('language_hint', models.CharField(blank=True, default='', max_length=50)),
                ('duration_min', models.PositiveSmallIntegerField(default=5)),
                ('icon_emoji', models.CharField(default='💼', max_length=10)),
                ('image_url', models.URLField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('completions_count', models.PositiveIntegerField(default=0)),
                ('system_prompt', models.TextField(help_text='Instructions pour le LLM : personnages, contexte, objectifs de la simulation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['category', 'difficulty'],
            },
        ),
    ]
