# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchange_index', models.PositiveSmallIntegerField()),
                ('ai_question', models.TextField()),
                ('ai_question_audio_url', models.URLField(blank=True, default='')),
                ('user_audio_url', models.URLField(blank=True, default='')),
                ('user_audio_duration_sec', models.FloatField(default=0)),
                ('transcription', models.TextField(blank=True, default='')),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('ai_response', models.TextField(blank=True, default='')),
                ('pronunciation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fluency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('phoneme_analysis', models.JSONField(blank=True, default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'audio_exchanges',
                'ordering': ['exchange_index'],
            },
        ),
        migrations.CreateModel(
            name='VocalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('conversation', 'Conversation libre'), ('simulation', 'Simulation professionnelle'), ('exercise', 'Exercice guidé'), ('level_test', 'Test de niveau')], max_length=50)),
                ('scenario', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20)),
                ('native_language_hint', models.CharField(blank=True, default='', max_length=50)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('exchanges_count', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'En cours'), ('processing', 'Traitement IA'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='simulations.simulation')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
