# Generated by Django 4.2.16 on 2026-04-14 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tspeak_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocalsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioexchange',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='tspeak_sessions.vocalsession'),
        ),
        migrations.AddIndex(
            model_name='vocalsession',
            index=models.Index(fields=['user', '-created_at'], name='sessions_user_id_06dff6_idx'),
        ),
        migrations.AddIndex(
            model_name='vocalsession',
            index=models.Index(fields=['status'], name='sessions_status_2c94db_idx'),
        ),
        migrations.AddIndex(
            model_name='vocalsession',
            index=models.Index(fields=['session_type'], name='sessions_session_d7ba02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audioexchange',
            unique_together={('session', 'exchange_index')},
        ),
    ]
